version: "3.7"
services:
        jekyll:
                image: jekyll/jekyll:${JEKYLL_VERSION}
                ports:
                        - "127.0.0.1:4000:4000"
                volumes:
                        - ".:/srv/jekyll:z"
                        - "./vendor/bundle:/usr/local/bundle:z"
